application: polyhack-1046
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /cheatsheet
  static_files: cheatsheet_dir/cheatsheet.html
  upload: cheatsheet\.html

- url: /style
  static_dir: style

- url: /cheat
  static_dir: cheatsheet_dir

- url: /script
  static_dir: script

- url: /img
  static_dir: img

- url: /sponsors
  static_dir: sponsors

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
